#!/usr/bin/env bash
#
# Rebuild the `space` branch and push it to Hugging Face Spaces.
#
# Why this exists
# ---------------
# HF Spaces reads its build config (sdk: docker, app_port: 7860) from YAML
# frontmatter at the very top of README.md. GitHub renders that same block as a
# metadata table above the title, which is noise on a portfolio repo. So `main`
# keeps a clean README, and this script derives a Space-only branch that puts
# the block back.
#
# `space` is a BUILD ARTEFACT, not a branch you work on: it is deleted and
# recreated from scratch on every run, then force-pushed. Never commit to it by
# hand — your commit would be discarded on the next sync.
#
# One-time setup
# --------------
#   git remote add space https://huggingface.co/spaces/<user>/<space-name>
#
# Usage
# -----
#   ./scripts/sync-space.sh              # rebuild from main and push
#   ./scripts/sync-space.sh --no-push    # rebuild locally, inspect, push yourself
#   SOURCE_BRANCH=develop ./scripts/sync-space.sh
#
set -euo pipefail

SOURCE_BRANCH="${SOURCE_BRANCH:-main}"
SPACE_BRANCH="${SPACE_BRANCH:-space}"
SPACE_REMOTE="${SPACE_REMOTE:-space}"
PUSH=1
[ "${1:-}" = "--no-push" ] && PUSH=0

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"
FRONTMATTER="deploy/hf-space-frontmatter.md"

die() { printf 'error: %s\n' "$1" >&2; exit 1; }

[ -f "$FRONTMATTER" ] || die "missing $FRONTMATTER"

# A dirty tree would be carried onto the Space branch or lost in the switch.
if ! git diff-index --quiet HEAD -- 2>/dev/null || [ -n "$(git status --porcelain)" ]; then
    die "working tree is not clean — commit or stash first"
fi

git show-ref --verify --quiet "refs/heads/$SOURCE_BRANCH" \
    || die "source branch '$SOURCE_BRANCH' does not exist"

if [ "$PUSH" -eq 1 ] && ! git remote get-url "$SPACE_REMOTE" >/dev/null 2>&1; then
    die "remote '$SPACE_REMOTE' is not configured. Run:
  git remote add $SPACE_REMOTE https://huggingface.co/spaces/<user>/<space-name>
Or rebuild locally without pushing:
  $0 --no-push"
fi

# Validate the source before touching any branch, so a bad source can never
# leave a half-built artefact behind.
git show "$SOURCE_BRANCH:README.md" >/dev/null 2>&1 \
    || die "'$SOURCE_BRANCH' has no README.md"
if git show "$SOURCE_BRANCH:README.md" | head -1 | grep -q '^---$'; then
    die "README.md on '$SOURCE_BRANCH' already starts with frontmatter.
'$SOURCE_BRANCH' is probably behind the remote. Update it first:
  git checkout $SOURCE_BRANCH && git pull --ff-only origin $SOURCE_BRANCH"
fi

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
BUILT=0
cleanup() {
    git checkout --quiet "$ORIGINAL_BRANCH" 2>/dev/null || true
    # Drop the artefact if we failed partway through building it.
    [ "$BUILT" -eq 0 ] && git branch --quiet -D "$SPACE_BRANCH" 2>/dev/null
    return 0
}
trap cleanup EXIT

echo "Rebuilding '$SPACE_BRANCH' from '$SOURCE_BRANCH'…"
git branch --quiet -D "$SPACE_BRANCH" 2>/dev/null || true
git checkout --quiet -b "$SPACE_BRANCH" "$SOURCE_BRANCH"

cat "$FRONTMATTER" README.md > README.space.md
mv README.space.md README.md

git add README.md
git commit --quiet -m "chore(space): add Hugging Face Spaces frontmatter

Generated by scripts/sync-space.sh from '$SOURCE_BRANCH'. Do not edit this
branch by hand — it is recreated on every sync."

BUILT=1
echo "  ✓ $SPACE_BRANCH built ($(git rev-parse --short HEAD))"

if [ "$PUSH" -eq 1 ]; then
    echo "Pushing to '$SPACE_REMOTE' ($(git remote get-url "$SPACE_REMOTE"))…"
    git push --force "$SPACE_REMOTE" "$SPACE_BRANCH:main"
    echo "  ✓ pushed — the Space will rebuild automatically"
else
    echo "  → not pushed. Inspect it, then:"
    echo "      git push --force $SPACE_REMOTE $SPACE_BRANCH:main"
fi
